### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mmatus1112** [dreimer1986/lovelace-animated-background#3]
Hi,

I have been trying to make this repository to work but no luck...

I have:

1) Uninstalled previous Animated Background installation
2) Removed the resources javascript from my dashboard
3) Restarted my HA
4) Reinstalled Animated Background. When installing, I see a message that the repository will be installed in /local/community/lovelace-animated-background
5) I go to my dashboard and I add the resource as a javascript -> /hacsfiles/lovelace-animated-background/animated-background.js
6) I go to my raw editing and I add the following:

''
animated_background:
  default_url: https://static.videezy.com/system/resources/previews/000/012/073/original/Fire_46_-_45s_-_4k_res.mp4
  opacity: 80
  entity: weather.kmia_daynight
  state_url:
    sunny:
      - https://cdn.flixel.com/flixel/hlhff0h8md4ev0kju5be.hd.mp4
      - https://cdn.flixel.com/flixel/zjqsoc6ecqhntpl5vacs.hd.mp4
      - https://cdn.flixel.com/flixel/jvw1avupguhfbo11betq.hd.mp4
      - https://cdn.flixel.com/flixel/8cmeusxf3pkanai43djs.hd.mp4
      - https://cdn.flixel.com/flixel/guwb10mfddctfvwioaex.hd.mp4
    partlycloudy:
      - https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4
      - https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4
      - https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4
      - https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4
      - https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4
      - https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4
    cloudy:
      - https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4
      - https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4
      - https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4
      - https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4
      - https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4
      - https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4
    mostlycloudy:
      - https://cdn.flixel.com/flixel/e95h5cqyvhnrk4ytqt4q.hd.mp4
      - https://cdn.flixel.com/flixel/l2bjw34wnusyf5q2qq3p.hd.mp4
      - https://cdn.flixel.com/flixel/rrgta099ulami3zb9fd2.hd.mp4
    clear-night:
      - https://cdn.flixel.com/flixel/x9dr8caygivq5secll7i.hd.mp4
      - https://cdn.flixel.com/flixel/v26zyfd6yf0r33s46vpe.hd.mp4
      - https://cdn.flixel.com/flixel/rosz2gi676xhkiw1ut6i.hd.mp4
    fog:
      - https://cdn.flixel.com/flixel/vwqzlk4turo2449be9uf.hd.mp4
      - https://cdn.flixel.com/flixel/5363uhabodwwrzgnq6vx.hd.mp4
    rainy: 
      - https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4
    pouring: 
      - https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4
    lightning: 
      - https://static.videezy.com/system/resources/previews/000/044/582/original/dark-forest.mp4
    lightning-rainy: 
      - https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4
views:
  - theme: ios-dark-mode
    path: default_view
    title: Home
    icon: ''
    badges:
      - entity: sun.sun
      .......
''

After all the steps, I still cannot see the animated background. Please help!

**Comment by wanmeich520** [comment]
the same problem as me

**Comment by mmatus1112** [comment]
> I smell the Browser Cache as culprit... In the big report I made in the original repo I fell for it, too. So hard that I fixed my faulty Cache with another JS file. ^^ [Villhellm#56](https://github.com/Villhellm/lovelace-animated-background/issues/56)
> 
> OK, first things first: /hacsfiles/lovelace-animated-background/animated-background.js looks good, but I am sure it's the same path as it was before with the original addon, right? If so, change it to: /hacsfiles/lovelace-animated-background/animated-background.js?v=10 This does not change anything on the script at all, but forces a reload in the browser Cache.
> 
> To finally force it, go back to main Dashboard and Push F12 to open the dev console. Move it aside and make a right click on the refresh button. Choose "Clear Cache and complete reload" or something like this. Then MAYBE it should work.
> 
> If it does and you ever have problems with it, you could try this one, too. https://github.com/dreimer1986/yourname_card_mod/blob/master/README-script.md This is my own madness that touches the whole way deeper in the website tree and thus is almost impossible to be ever b0rked by any update.
> 
> If not, tell me ^^

Thank you for the response! So I have followed your steps but no luck. I did the following:

1) Uninstalled "animated background" from HACS.
2) Made sure the "Lovelace Dashboard Animated Background Resource" was removed.
3) Cleared my "Edge" cache from ALL TIME.
4) Restarted my browser.
5) Reinstall "lovelace animated background" in HACS. I insist that I get the following message in the pop-up window "When downloaded this will be located in '/config/www/community/lovelace-animated-background'" Please note I am installing version 0.6.3
6) When I go to add the "Lovelace Dashboard Animated Background Resource", I see that a resource is added automatically -> /hacsfiles/lovelace-animated-background/animated-background.js?hacstag=202743061063
7) Should I keep that one or add the one stated in the repository description > /hacsfiles/lovelace-animated-background/animated-background.js?
8) If I leave the one added automatically, and copy the code of Step 3, it does not work. I refresh my web browser but still no luck.
9) If I delete the resource added automatically and copy the one stated in Step 2, it still does not work.
10) If I add the repository as you stated in your comment ->  /hacsfiles/lovelace-animated-background/animated-background.js?v=10, still no luck.

Any other suggestions?

**Comment by dreimer1986** [comment]
Try another browser to be sure it's not still some leftover cache.

**Comment by dreimer1986** [comment]
Status?

**Comment by mmatus1112** [comment]
Alright, so here is my take on this:

1) If I try the HACS method of installation, it does not work.
2) If I try the manual installation, it works perfectly.

Not really sure what the issue is with the HACS method of installation but I was not able to make it work.

Thanks!!!

**Comment by dreimer1986** [comment]
Hmm... ok? Strange. I wonder what is different in that case. In theory nothing should differ file wise at least.
