### ISSUE TITLE
WHERE IS UI_LOVELACE.YAML ?

### ISSUE THREAD

**Issue by Truehub23** [dreimer1986/lovelace-animated-background#6]
Then you don't understand anything at all in the guide, a whole series of pre-requisites are missing, probably which you didn't specify and which are part of old versions of HS.

Once the Animated integration has been downloaded from HACS it is absolutely not clear what to do: where is the file you say to edit "ui-lovelace.yaml" located? Exists? There is no path, there is no reference to lovelace in a clean installation of the latest version of HS OS.

Please explain carefully the next steps after downloading the animated module on HACS, thanks,

**Comment by dreimer1986** [comment]
ui-lovelace.ymal is in .storage folder inside your /config folder. Lovelace is a old naming of the new Dashboard from older HA versions. This thing is not really maintained anymore as I made my own way to get animated backgrounds without all the problem this way even with hackfixes causes on new HA versions.

https://github.com/dreimer1986/yourname_card_mod/blob/master/README-script.md Check this one. Here I welcome you more than a bit to tell me if you don't understand something. This one is no install and forget variant. You need to tinker a bit, but I tried to have all the needed stuff in this readme.
